spring:
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
#    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  web:
    resources:
      static-locations: # 리소스 위치 명시적 설정
        - classpath:/static/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/public/
        - file:./upload/popUp/ # .은 루트 폴더를 의미함
        # 아래처럼 사용하면 됨. 폴더 생성은 popUp 서비스 참고해서 만들어야함.
        # - file:./upload/board/
        # - file:./upload/profile/
      static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB   # 단일 파일의 최대 크기
      max-request-size: 50MB # 요청 전체의 최대 크기

file:
  upload:
    base-dir: upload
    directories:
      board: C:/upload/board
      board-temp: C:/upload/board/temp  # 임시 저장 경로 추가
      # 아래 처럼 사용하면됨.
      # board: ${file.upload.base-dir}/board
      # profile: ${file.upload.base-dir}/profile