spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # Hibernate? ???? ????? ??
    defer-datasource-initialization: true # ??? ?? ? data.sql ??
    show-sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always # ?? ??
      data-locations: classpath:db/data.sql # ??? ?? ??
